### ISSUE TITLE
Could not resolve hostname [IP ADRESS]: Name or service not known

### ISSUE THREAD

**Issue by PaxtonPenguin** [SHA65536/arcade#1]
I've got an error using ssh to connect and I've got  this error:

Could not resolve hostname 127.0.0.1:9992: Name or service not known
(127.0.0.1:9992 is my hosting ip)

**Comment by SHA65536** [comment]
Hey I can't know what's wrong without more info, what did you run, 127.0.0.1 is localhost so unless you're trying to access from the same machine you're running it ok then it's not going to work. Regardless, there's nothing in this project yet, it's not done so I'm not sure what you're trying to do.
